apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: backend-timeout
  namespace: notes
spec:
  hosts:
  - canary-backend
  http:
  - timeout: 1s
    route:
    - destination:
        host: canary-backend