apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-frontend
  namespace: notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-frontend
  template:
    metadata:
      labels:
        app: canary-frontend
    spec:
      containers:
        - name: frontend
          image: mrigankwastaken/canary-resilience-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: API_BASE_URL
              value: "http://canary-backend:3000"
